import os


def write_xyz_file(filename, atoms, coordinates):
    """
    Writes an .xyz file.

    :param filename: Name of the .xyz file to create.
    :param atoms: List of atomic symbols, e.g., ['C', 'H', 'O'].
    :param coordinates: List of coordinates, where each coordinate is a list [x, y, z].
    """
    num_atoms = len(atoms)

    if not (num_atoms == len(coordinates)):
        raise ValueError("Number of atoms and number of coordinates must be the same.")

    with open(filename, 'w') as f:
        # Write the number of atoms
        f.write(f"{num_atoms}\n")
        # Write a comment line (can be empty or a description)
        f.write("Generated by python script\n")

        # Write the atomic symbols and coordinates
        for atom, coord in zip(atoms, coordinates):
            f.write(f"{atom} {coord[0]:.6f} {coord[1]:.6f} {coord[2]:.6f}\n")

if __name__ == "__main__":
    # Example usage
    atoms = ['C', 'H', 'H', 'H', 'H']
    coordinates = [
        [0.000000, 0.000000, 0.000000],
        [0.000000, 0.000000, 1.089000],
        [1.026719, 0.000000, -0.363000],
        [-0.513360, 0.889165, -0.363000],
        [-0.513360, -0.889165, -0.363000]
    ]

    write_xyz_file('molecule.xyz', atoms, coordinates)